### PR TITLE
Make repo as obsolete

### PR DESCRIPTION
**Pull request by MarceloSalazar**
FYI @geky @AnotherButler

### CODE REVIEW

**Comment by MarceloSalazar** [comment]
cc @sg- @adbridge

**Review by geky — APPROVED** [review]

**Comment by geky** [comment]
We can also put "[obsolete]" in the repo description.

When are we planning on merging this?

**Review by geky — APPROVED** [review]

**Comment by MarceloSalazar** [comment]
> When are we planning on merging this?

As soon as @sg- is happy with this :)

**Review by sg- — APPROVED** [review]
LGTM

**Comment by geky** [comment]
@theotherjimmy, that's your cue

**Pull request merged**
