### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MarceloSalazar**
Point at docs for troubleshooting. 

@theotherjimmy @geky @AnotherButler

### CODE REVIEW

**Review by AnotherButler — APPROVED** [review]

**Review by AnotherButler — APPROVED** [review]

**Review by geky — APPROVED** [review]

**Comment by adbridge** [comment]
@geky can this now be merged then please ? Do these changes also need to propogate across to the new single example, mbed-os-example-filesystem ?

**Comment by geky** [comment]
I only just realized I don't actually have permissions to merge on this repo. @theotherjimmy? (also @AnotherButler might?).

The changes will need to be copied manually.

EDIT: Copied the changes over here:
https://github.com/ARMmbed/mbed-os-example-filesystem/pull/6

**Comment by geky** [comment]
Copied the changes over:
https://github.com/ARMmbed/mbed-os-example-filesystem/pull/6

**Comment by AnotherButler** [comment]
I don't have permissions for most of the examples (or I didn't as of last night), but it looks like I do for this one. Would you like me to wait for @theotherjimmy or to merge now?

**Comment by geky** [comment]
I just noticed cause your checkmark was green.

Either way looks like @theotherjimmy answered the question XD

**Pull request merged**
